/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignmentone;

import java.util.Scanner;

/**
 * This is the main class for the assignment.
 */
public class App {
  private Scanner input;

  private App(Scanner scannerInput) {
    this.input = scannerInput;
  }

  /**
   * Solution to first task.
   */
  public void helloThere() {
    System.out.print("Name, please: ");
    String name = input.nextLine();

    var hello = new HelloThere();
    System.out.println(hello.hello(name));

  }

  /**
   * Solution for the second task.
   */
  public void seconds() {

    Time time = new Time();

    System.out.print("Enter hours, minutes and seconds: ");
    String enterThree = input.nextLine();

    int[] values = time.threeInt(enterThree);
    int h = values[0];
    int m = values[1];
    int s = values[2];

    System.out.print("In only seconds that is: ");
    System.out.println(time.toSeconds(h, m, s));


  }

  /**
   * Solution for the third task.
   */
  public void imInaBand() {
    Album album = new Album("Wish You Were Here", 1975, "Pink Floyd");

    System.out.println(album.getName() + " was released in " 
        + album.getYear() + " by " + album.getArtist());

  }

  /**
   * Solution for the fourth task.
   */
  public void bestAlbumsEver() {
    AlbumGenerator albums = new AlbumGenerator();
    Album[] arrayAlbums = albums.generateAlbums();
    
    for (Album e : arrayAlbums) {
      System.out.println(e.getName() + " was released in " 
          + e.getYear() + " by " + e.getArtist());
    }
  }

  /**
   * Solution for the fifth task.
   */
  public void workingWithArrays() {
    
    ArrayAlgorithms array = new ArrayAlgorithms();

    System.out.println("Enter an array of numbers:");
    // input the different numbers as a whole String
    String arrayInString = input.nextLine();
    // divide the serie of numbers into an array of number but as Strings
    String[] numbersInString = arrayInString.split(" ");

    // Get the real size of an array. Correct in case supplementary spaces
    // are entered, different than numbersInString.length
    int realSizeIntArr = array.realSizeArray(numbersInString);

    //initialize an array of the length of the string array of number
    int[] changed = array.fromStringtoIntArray(numbersInString, realSizeIntArr); 

    // Call the average method
    double avav = array.average(changed);
    System.out.println("Average is: " + avav);

    // Call the maximum value method
    int largestValue = array.maxValue(changed);
    System.out.println("Largest value is: " + largestValue);

    int indexSmall = array.minIndex(changed);
    System.out.println("Index of smallest value at position: " + indexSmall);

    int[] shiftedArray = array.shift(changed);
    System.out.println("Shifted array:");
    for (int e : shiftedArray) {
      System.out.print(e + " ");
    }
    System.out.println();

    int[] shuffledArray = array.shuffle(changed);
    System.out.println("Shuffled array:");
    for (int e : shuffledArray) {
      System.out.print(e + " ");
    }
    System.out.println();
  }

  /**
   * Starting point of the first assignment.
   *
   * @param args is not used.
   */
  public static void main(String[] args) {
    

    // we create a scanner object to work with
    // it is advised to create one and only one scanner for a specific 
    // stream in the whole application
    // scanners should be closed when you are done and this also closes the underlying stream
    Scanner consoleInput = new Scanner(System.in, "UTF-8");

    App app = new App(consoleInput);

    // Task 1
    app.helloThere();

    // Task 2
    app.seconds();

    // Task 3
    app.imInaBand();

    // Task 4 
    app.bestAlbumsEver();

    // Task 5
    app.workingWithArrays();

    // now we are exiting the application so time to close the scanner.
    consoleInput.close();
  }
}
