/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package solarsystem;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import solarsystem.filewriter.FileHandler;
import solarsystem.heavenlybodies.HeavenlyBody;

/**
 * This is the main class where the program runs.
 */
public class Main {
  /**
   * Main method that runs the program.

   * @param args are arguments.
   * @throws SecurityException is a security exception.
   * @throws IOException is a IO exception.
   */
  public static void main(String[] args) throws SecurityException, IOException {
    System.out.println("Welcome to the solar system");
    List<HeavenlyBody> solarsystem = new ArrayList<>();
    FileHandler fileHandler = new FileHandler();
    solarsystem = fileHandler.setUpTheSystem(solarsystem);

    HbPrincipal menuPrincipal = new HbPrincipal(solarsystem);
    menuPrincipal.principalMenu();

    System.out.println("Bye and welcome back!");
  }
}
